steps:
  - name: 'node:20-alpine'
    entrypoint: npm
    args: ['install']

  - name: 'node:20-alpine'
    entrypoint: npm
    args: ['test']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/jogo-do-ano', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/jogo-do-ano']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - jogo-do-ano
      - --image=southamerica-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/jogo-do-ano
      - --region=southamerica-east1
      - --platform=managed
      - --allow-unauthenticated
      - --min-instances=0
      - --max-instances=2
      - --memory=256Mi
      - --cpu=1
      - --timeout=3600
      - --port=3000
      - --quiet

images:
  - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/jogo-do-ano'

options:
  logging: CLOUD_LOGGING_ONLY
